var  config_path = "../php/json.php?"
	,uplad_path = "../php/upload.php?" 
    
    ,config_path__basic_parameter__grid =         config_path+"class=basic_parameter&function=grid"    
    ,config_path__basic_parameter__resetMemory =  config_path+"class=basic_parameter&function=resetMemory"
    ,config_path__basic_parameter__add =          config_path+"class=basic_parameter&function=add"    
    ,config_path__basic_parameter__remove =       config_path+"class=basic_parameter&function=remove"    
    ,config_path__basic_parameter__data =         config_path+"class=basic_parameter&function=data"        
                            
    ,config_path__basic_user__login =             config_path+"class=basic_user&function=login"    
    ,config_path__basic_user__logout =            config_path+"class=basic_user&function=logout"    
    ,config_path__basic_user__updateSession =     config_path+"class=basic_user&function=updateSession"    
    ,config_path__basic_user__grid =              config_path+"class=basic_user&function=grid"    
    ,config_path__basic_user__grid_more =         config_path+"class=basic_user&function=grid_more"    
    ,config_path__basic_user__add =               config_path+"class=basic_user&function=add"    
    ,config_path__basic_user__add_register =      config_path+"class=basic_user&function=add_register"    
    ,config_path__basic_user__remove =            config_path+"class=basic_user&function=remove"    
    ,config_path__basic_user__modify =            config_path+"class=basic_user&function=modify"    
    ,config_path__basic_user__view =              config_path+"class=basic_user&function=view"    
  
    ,config_path__basic_group__add =              config_path+"class=basic_group&function=add"        
    ,config_path__basic_group__modify =           config_path+"class=basic_group&function=modify"        
    ,config_path__basic_group__view =             config_path+"class=basic_group&function=view"        
    ,config_path__basic_group__remove =           config_path+"class=basic_group&function=remove"        
    ,config_path__basic_group__permission_get =   config_path+"class=basic_group&function=permission_get"        
    ,config_path__basic_group__permission_set =   config_path+"class=basic_group&function=permission_set"        
    ,config_path__basic_group__grid =             config_path+"class=basic_group&function=grid"         
    ,config_path__basic_group__treegrid =         config_path+"class=basic_group&function=treegrid" 
    ,config_path__basic_group__register =         config_path+"class=basic_group&function=register"             
        
    ,config_path__exam_paper__grid =            config_path+"class=exam_paper&function=grid"
    ,config_path__exam_paper__remove =          config_path+"class=exam_paper&function=remove"
    ,config_path__exam_paper__view =            config_path+"class=exam_paper&function=view"        
    ,config_path__exam_paper__submit =          config_path+"class=exam_paper&function=submit"
    ,config_path__exam_paper__modify =          config_path+"class=exam_paper&function=modify"  
    ,config_path__exam_paper__upload_img =      config_path+"class=exam_paper&function=upload_img"
    ,config_path__exam_paper__upload =          config_path+"class=exam_paper&function=upload"      
    ,config_path__exam_paper__download =        config_path+"class=exam_paper&function=download"    
    ,config_path__exam_paper__questions =       config_path+"class=exam_paper&function=questions"
        
    ,config_path__exam_paper_multionline__grid =            config_path+"class=exam_paper_multionline&function=grid"
    ,config_path__exam_paper_multionline__remove =          config_path+"class=exam_paper_multionline&function=remove"
    ,config_path__exam_paper_multionline__modify =          config_path+"class=exam_paper_multionline&function=modify"      
    ,config_path__exam_paper_multionline__view =            config_path+"class=exam_paper_multionline&function=view"        
    ,config_path__exam_paper_multionline__submit =          config_path+"class=exam_paper_multionline&function=submit"
    ,config_path__exam_paper_multionline__upload =          config_path+"class=exam_paper_multionline&function=upload"      
    ,config_path__exam_paper_multionline__download =        config_path+"class=exam_paper_multionline&function=download"    
    ,config_path__exam_paper_multionline__order =           config_path+"class=exam_paper_multionline&function=order"   
    ,config_path__exam_paper_multionline__close =           config_path+"class=exam_paper_multionline&function=close"   
        
    ,config_path__exam_subject__add =           config_path+"class=exam_subject&function=add"       
    ,config_path__exam_subject__remove =        config_path+"class=exam_subject&function=remove"  
    ,config_path__exam_subject__modify =        config_path+"class=exam_subject&function=modify"      
    ,config_path__exam_subject__view =          config_path+"class=exam_subject&function=view"     
    ,config_path__exam_subject__group_get =     config_path+"class=exam_subject&function=group_get"     
    ,config_path__exam_subject__group_set =     config_path+"class=exam_subject&function=group_set"     
    ,config_path__exam_subject__grid =          config_path+"class=exam_subject&function=grid"      
    ,config_path__exam_subject__treegrid =      config_path+"class=exam_subject&function=treegrid"      
    ,config_path__exam_subject__getMy =         config_path+"class=exam_subject&function=getMy"         
        
    ,config_path__exam_paper_log__grid =            config_path+"class=exam_paper_log&function=grid"
    ,config_path__exam_paper_log__remove =          config_path+"class=exam_paper_log&function=remove"  
    ,config_path__exam_paper_log__questions =       config_path+"class=exam_paper_log&function=questions"
    ,config_path__exam_paper_log__submit =          config_path+"class=exam_paper_log&function=submit"
        
    ,config_path__exam_question_log_wrongs__grid =              config_path+"class=exam_question_log_wrongs&function=grid"
    ,config_path__exam_question_log_wrongs__remove =            config_path+"class=exam_question_log_wrongs&function=remove"        
    ,config_path__exam_question_log_wrongs__questions =         config_path+"class=exam_question_log_wrongs&function=questions"
        
    ,config_path__exam_subject_2_user_log__grid =               config_path+"class=exam_subject_2_user_log&function=grid"             
    ,config_path__exam_subject_2_user_log__getMySub =           config_path+"class=exam_subject_2_user_log&function=getMySub"        
    ;        